version: '3.8'
services:
  mongodb:
    image: mongo  # 镜像
    container_name: mongodb_product  # 容器名称
    ports:
      - "27017:27017"  # 主机27017端口映射到容器的27017端口（默认端口）
    volumes:
      - mongodb-data:/data/db  # 创建名为 mongodb-data 的卷，映射到容器的 /data/db（MongoDB 默认数据目录）
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin  # 启用认证，设置用户名
      - MONGO_INITDB_ROOT_PASSWORD=secret  # 启用认证，设置密码
volumes:
  mongodb-data:
networks:
  mongo-network:
    driver: bridge